FROM golang:1.23.6 AS builder
WORKDIR /go/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN GOOS=linux go build -o backend-bin main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root/
COPY --from=builder /go/src/app/backend-bin .

EXPOSE 8080
CMD ["./backend-bin"]
